### ISSUE TITLE
Push 3.1.2 changes to GitHub

### ISSUE THREAD

**Issue by streeter** [tougher/Brushes#12]

**Comment by loadmemo** [comment]
I need the 3.1.2 changes too. I want's to know how to fix the black artifacts when drawing in iPhone 6 (Plus)

**Comment by afektmedia** [comment]
Any update here on tbe 3.1.2 version that fixed the artifacts on ipaf air 2 and iphone 6. Hopefully Tougher can give us an update or word of how he fixed it as version here still causes artifacting. Hope we havn't lost his support here😢

**Comment by tougher** [comment]
See https://github.com/tougher/Brushes/issues/16
