### ISSUE TITLE
Upload to Dropbox

### ISSUE THREAD

**Issue by tallwhiteboy501** [tougher/Brushes#3]
When I try to upload my Brushes file to dropbox the app suddenly quits and never actually uploads.  It will do this every time I attempt it.

I have an iPad 2 running iOS 8.1.1

Thank you

**Comment by tougher** [comment]
Fixed!

**Comment by BJeany** [comment]
I'm a complete newbie; just downloaded Brushes Redux to my elderly EOL iPad only to find no tutorial and the app routinely crashes when I touch the settings "gear," so I have no way of knowing what the settings might control. My point of reference for how the app might work is Photoshop; I have a reference file I would like to use to get colors right as I'm wanting to design a glaze for some pottery I've made. The App Store sent me to GitHub for support for the app, but I don't see much. 

Help?
